<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository
{
    public function getZoneAffectation(){

        $query = $this->_em->createQuery("SELECT z FROM OCPlatformBundle:Zone z");
        
        $results = $query->getResult();
        return $results;

    }

}
